/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface PartialHashGlobOptions {
  cwd?: string
  gitignore?: boolean
  concurrency?: number
}
export declare function hashGlobXxhash(globs: Array<string>, maybeOptions?: PartialHashGlobOptions | undefined | null): Record<string, bigint | undefined | null> | null
export declare function hashGlobGit(globs: Array<string>, maybeOptions?: PartialHashGlobOptions | undefined | null): Record<string, string | undefined | null> | null
export declare function hash(files: Array<string>, maybeOptions?: PartialHashGlobOptions | undefined | null): Record<string, string | undefined | null> | null
export declare function glob(globs: Array<string>, maybeOptions?: PartialHashGlobOptions | undefined | null): Array<string> | null
export interface StatEntry {
  mtime: bigint
  size: number
}
export declare function stat(files: Array<string>, maybeOptions?: PartialHashGlobOptions | undefined | null): Record<string, StatEntry> | null
